# Generated by Django 3.2.8 on 2021-10-11 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=200)),
                ('adres', models.CharField(max_length=200)),
                ('complete', models.BooleanField()),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vineyards.domaine')),
            ],
        ),
    ]
