# Generated by Django 3.2.8 on 2021-10-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=500)),
                ('contact', models.EmailField(max_length=200)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
