# Generated by Django 3.2.8 on 2021-10-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0002_helpmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='adres',
            new_name='vilage',
        ),
    ]
