# Generated by Django 3.2.8 on 2021-10-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(max_length=200)),
                ('host_name', models.CharField(max_length=50)),
                ('surname_host', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('region', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('experience', models.TextField(max_length=250)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
